name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false



      - name: Setup Node.js ⚙️
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20
          cache: 'npm'

      - name: Initialize (Install Deps) 📦
        run: make init

      - name: Build for GitHub Pages 🏗️
        # We extract the repository name automatically (e.g., "user/repo" -> "repo")
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          make build-gh REPO_NAME=$REPO_NAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          folder: dist/swimming-game/browser # Update 'swimming-game' if your package.json name differs
          branch: gh-pages
